application:
  bindAddress: :8443
  production: false
  debug: false
routes:
#  keycloak-admin:
#    prefix: /auth/admin
#    url: http://tradalia-server:8444
  keycloak:
    prefix: /auth
    url: https://tradalia-server:8448
  inventory-server:
    prefix: /api/inventory
    url: https://tradalia-server:8447/api/inventory
  portfolio-trader:
    prefix: /api/portfolio
    url: https://tradalia-server:8445/api/portfolio
  system-adapter:
    prefix: /api/system
    url: https://tradalia-server:8449/api/system
  data-collector:
    prefix: /api/collector
    url: https://tradalia-server:8446/api/collector
  storage-manager:
    prefix: /api/storage
    url: https://tradalia-server:8452/api/storage
  doc-editor:
    prefix: /doc-editor
    url: http://tradalia-server:8453/doc-editor
  frontend:
    prefix: /
    url: http://tradalia-server:8444
